# 项目相关配置
whiteget:
  # 名称
  name: WhiteGet
  # 版本
  version: 1.0.0
  # 版本年份
  copyrightYear: 2019

# 开发环境配置
server:
  # 服务器的HTTP端口，默认8081
  port: 8081
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数
    max-threads: 800
    # Tomcat启动初始化线程数
    min-spare-threads: 30

# 日志配置
logging:
  level:
    com.whiteget: debug
    org.springframework: warn

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: dev
  # 服务模块
  devtools:
    restart:
      # 热部署
      enabled: true
  banner:
    location: banner.txt

# MyBatis-plus
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.whiteget.project,com.whiteget.system
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath:mapper/**/*Mapper.xml
  global-config:
    db-config:
      id-type: AUTO
      capitalMode: true
  configuration:
    cache-enabled: false

shiro:
  user:
    loginUrl: /login
    successUrl: /index
    unauthorizedUrl: /unauth


