whiteget:
  project-name: white_get
  project-root-u-r-l: http://localhost:8080/
  demoMode: false
  devMode: true
  jwt:
    userPrimaryKey: userId
    expireTime: 3000000
    refreshTokenExpire: 86400000
logging:
  level:
    com.ifast: debug
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/whiteget?useUnicode=true&characterEncoding=utf8&useSSL=true&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    druid:
      #初始连接数
      initial-size: 5
      #最小连接池数量
      min-idle: 10
      #最大连接池数量
      max-active: 20
      #最大超时时间（毫秒）
      max-wait: 60000
      #1.间隔多久才进行一次检测，2.检测需要关闭的空闲连接（毫秒）
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间（毫秒）
      min-evictable-idle-time-millis: 300000
      #一个连接在池中最大生存的时间（毫秒）
      max-evictable-idle-time-millis: 900000
      #检测连接是否有效
      validation-query: SELECT 1 FROM DUAL
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 2000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
